name: Golang

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DOCKER_BUILDKIT: 1

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Repo
        uses: actions/checkout@v3
      
      - name: Run tests
        run: make unit-test

      - name: Run linter
        run: make lint
      
      - name: Build
        run: make
      
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: |
            bin/app